{% set name = "etcd" %}
{% set version = "3.3.8" %}

{% set sha256 = "574323d4cf5d17db0445a5eb007d7ed27ad4bd0ebf9ef00af2064bfe81242182" %}
{% set sha256_win64 = "75efa4e331a515b398266f20babd710ebed6d4b67090b164f5ed54d446d58312" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coreos/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  url: https://github.com/coreos/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}-windows-amd64.zip  # [win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: {{ sha256 }}  # [not win]

  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: {{ sha256_win64 }}  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - go 1.9.*  # [not win]
    - git  # [not win]
    - make  # [not win]
    - toolchain  # [not win]

test:
  commands:
    - etcd --version
    - etcdctl --version

    # Ugly hack because etcd&etcdclt are not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [osx]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://coreos.com/etcd/
  license: Apache-2.0
  license_family: Apache
  summary: A distributed, reliable key-value store for the most critical data of a distributed system.
  doc_url: https://coreos.com/etcd/docs/{{ version }}/index.html
  dev_url: https://github.com/coreos/etcd

extra:
  recipe-maintainers:
    - sodre
