{% set name = "etcd" %}
{% set version = "3.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/coreos/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 0452a98bd485d757fd85d2182f8eac8c2dad315bcb6cf29a797ced9e2669c413  # [not win]

  url: https://github.com/coreos/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}-windows-amd64.zip  # [win]
  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: 05eb68132ce06a37704da595f17ee33b65ee1e4cf9a6e5ed947d9b74538c3798  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - make  # [not win]
    - git  # [not win]

test:
  commands:
    - etcd --version
    - etcdctl --version

    # Ugly hack because etcd&etcdclt are not a dynamic executable
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [osx]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]

about:
  home: https://coreos.com/etcd/
  license: Apache-2.0
  license_family: Apache
  summary: A distributed, reliable key-value store for the most critical data of a distributed system.
  doc_url: https://coreos.com/etcd/docs/{{ version }}/index.html
  dev_url: https://github.com/coreos/etcd

extra:
  recipe-maintainers:
    - sodre
