travis:
  secure:
    BINSTAR_TOKEN: E/SLhckvo3UVE0jjZ6tw2s5dtApnJG1Fu/irJE6CVtzXxouUaR5bs0Vf/iTzYT7Un+47l/nH9KH7K+2yjJMHFiWBFphXDH7yojmf1sjsm6pGwkJUGoipCdhqIE5ny+s0rXshGR0rq4tpKT4mvTK88XND7OfPL9+Vib7K4f3BYRl0r+JjN4tyxM10N4DV9D0OYkEz8+mYQ2S0Za06Dq7bPjVfGkhfHhzQD8xdJ19sR95Un9j7VC3081GT23+8IEtvrdaq0TC7xuo4eBXYst7KN4S4YilU6vdEmn5vMOxE3AH3a2SedulyBL5i8XlPIHKjdKsi1YZOEvfdVcnX95PJ5GOtS5h+R2tlEE3lpryujA7hYdcXGoA72jwy32hAO37lnvDmSsiOCFkyyPAHixCsebPSsjF1h1qTfFsp+4f/BealxElwvnXjwbUqsezfZJgsnPEzMu6o447/sophPhJkisI0adplouxijMNivrt9iZeEnNA/a1G/Eq72GK9ZNttfFcZsWlWhnYJf/ZK3XeVZBo8wBOGumG2SLC4REpWOFPCOtlquEkFQSZG8VWoblScmqpBoinIa1w4sQ12plizwhFsxo6/7pLv2Bi/27NZz0lULJn+gBwZUz2wfDZm2wUWCbi6TVMjml4XORTaUTJ9VKTj7J1QZRQ40azJIADoOHNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
